# Generated by Django 5.2.5 on 2025-08-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(db_column='video_id', primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100)),
                ('location', models.FileField(upload_to='video/')),
                ('fecha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
